version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: bobgoze/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    image: bobgoze/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: bobgoze/kittygram_gateway
    env_file: .env
    ports:
      - "${GATEWAY_CONTAINER_PORT}:${GATEWAY_HOST_PORT}"

    volumes:
      - static:/static
      - media:/media
